"""Turn 16-bit QMK keycodes into short legends for a Finnish host layout.

The data file (data/keycodes.json) is generated by tools/keymap/gen_layers.py
from QMK's keycode spec, keymap_finnish.h and the keymap's own custom keycodes.
It holds exact legends for every code the keymap uses or the Finnish header
defines; anything else is decoded from QMK's keycode ranges, so a keymap that
was changed live in VIA still gets sensible labels.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from importlib import resources
from typing import Any

# Categories shared with the firmware's RGB layer guide (features/rgb_layers.c).
NONE, ALPHA, SYMBOL, DIGIT, NAV, EDIT, MOD, LAYER, SYSTEM, DANGER = (
    "none", "alpha", "symbol", "digit", "nav", "edit", "mod", "layer", "system", "danger",
)  # fmt: skip

MOD_NAMES = {0x01: "Ctl", 0x02: "Sft", 0x04: "Alt", 0x08: "GUI"}


@dataclass(frozen=True)
class Key:
    legend: str
    sub: str = ""  # small second line, e.g. "dead" or a hold action
    category: str = SYMBOL
    layer: int | None = None  # target layer of a layer key


def load_data() -> dict[str, Any]:
    text = resources.files("layer_overlay").joinpath("data/keycodes.json").read_text(encoding="utf-8")
    return json.loads(text)


class Decoder:
    def __init__(self, data: dict[str, Any] | None = None, layer_names: list[str] | None = None) -> None:
        data = data if data is not None else load_data()
        self.names: dict[int, str] = {int(k, 16): v for k, v in data["names"].items()}
        self.legends: dict[int, list[str]] = {int(k, 16): v for k, v in data["legends"].items()}
        self.categories: dict[int, str] = {int(k, 16): v for k, v in data.get("categories", {}).items()}
        self.ranges: dict[str, tuple[int, int]] = {k: (v[0], v[1]) for k, v in data["ranges"].items()}
        self.layer_names = layer_names or []

    def _in(self, code: int, name: str) -> bool:
        lo, hi = self.ranges.get(name, (1, 0))
        return lo <= code <= hi

    def layer_name(self, layer: int) -> str:
        if 0 <= layer < len(self.layer_names):
            return self.layer_names[layer]
        return f"L{layer}"

    def decode(self, code: int) -> Key:
        if code in self.legends:
            legend = self.legends[code]
            return Key(legend[0], legend[1] if len(legend) > 1 else "", self.category(code), self._layer_of(code))
        if self._in(code, "QK_MOMENTARY"):
            return Key(self.layer_name(code & 0x1F), "hold", LAYER, code & 0x1F)
        if self._in(code, "QK_TOGGLE_LAYER"):
            return Key(self.layer_name(code & 0x1F), "toggle", LAYER, code & 0x1F)
        if self._in(code, "QK_TO"):
            return Key(self.layer_name(code & 0x1F), "to", LAYER, code & 0x1F)
        if self._in(code, "QK_ONE_SHOT_LAYER"):
            return Key(self.layer_name(code & 0x1F), "1-shot", LAYER, code & 0x1F)
        if self._in(code, "QK_LAYER_TAP_TOGGLE"):
            return Key(self.layer_name(code & 0x1F), "tap-tog", LAYER, code & 0x1F)
        if self._in(code, "QK_LAYER_TAP"):
            tap = self.decode(code & 0xFF)
            layer = (code >> 8) & 0x0F
            return Key(tap.legend, self.layer_name(layer), LAYER, layer)
        if self._in(code, "QK_MOD_TAP"):
            tap = self.decode(code & 0xFF)
            return Key(tap.legend, self._mods((code >> 8) & 0x1F), MOD)
        if self._in(code, "QK_MODS"):
            base = self.decode(code & 0xFF)
            return Key(base.legend, self._mods((code >> 8) & 0x1F), self.category(code))
        if self._in(code, "QK_USER"):
            return Key(f"U{code - self.ranges['QK_USER'][0]}", "", SYSTEM)
        name = self.names.get(code)
        if name:
            for prefix in ("KC_", "QK_", "RM_", "MS_"):
                if name.startswith(prefix):
                    name = name[len(prefix) :]
                    break
            return Key(name.replace("_", " ").title()[:6], "", self.category(code))
        return Key(f"{code:04X}", "", SYSTEM)

    def _layer_of(self, code: int) -> int | None:
        for r in ("QK_MOMENTARY", "QK_TOGGLE_LAYER", "QK_TO", "QK_ONE_SHOT_LAYER", "QK_LAYER_TAP_TOGGLE"):
            if self._in(code, r):
                return code & 0x1F
        return None

    @staticmethod
    def _mods(m: int) -> str:
        right = m & 0x10
        parts = [n for bit, n in MOD_NAMES.items() if m & bit]
        if right and parts == ["Alt"]:
            return "AltGr"
        return "+".join(("R" if right else "") + p for p in parts)

    def category(self, code: int) -> str:
        if code in self.categories:
            return self.categories[code]
        if code in (0x0000, 0x0001):
            return NONE
        name = self.names.get(code, "")
        if name in ("QK_BOOTLOADER", "QK_REBOOT", "QK_CLEAR_EEPROM"):
            return DANGER
        if name in ("QK_LAYER_LOCK",) or self._layer_of(code) is not None or self._in(code, "QK_LAYER_TAP"):
            return LAYER
        if 0xE0 <= code <= 0xE7 or name in ("QK_CAPS_WORD_TOGGLE", "KC_CAPS_LOCK") or self._in(code, "QK_MOD_TAP"):
            return MOD
        basic = code & 0xFF if self._in(code, "QK_MODS") else code
        mods = (code >> 8) & 0x1F if self._in(code, "QK_MODS") else 0
        if mods & 0x09 and not mods & 0x06:  # Ctrl/GUI shortcuts
            if basic in (0x50, 0x4F, 0x4B, 0x4E):  # word / tab navigation
                return NAV
            return EDIT
        if code <= 0xFF or (mods and not mods & 0x09):
            if 0x04 <= basic <= 0x1D or basic in (0x2F, 0x33, 0x34):  # letters incl. Å Ö Ä
                return ALPHA if not mods else SYMBOL
            if 0x1E <= basic <= 0x27:
                return DIGIT if not mods else SYMBOL
            if 0x3A <= basic <= 0x45 or 0x68 <= basic <= 0x73 or 0x53 <= basic <= 0x63:
                return DIGIT
            if 0x4F <= basic <= 0x52 or basic in (0x4A, 0x4B, 0x4D, 0x4E):
                return NAV
            if basic in (0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x49, 0x4C):
                return EDIT
            if 0xA5 <= basic <= 0xFF:
                return SYSTEM
            return SYMBOL
        if self._in(code, "QK_LIGHTING") or self._in(code, "QK_QUANTUM") or self._in(code, "QK_USER"):
            return SYSTEM
        return SYMBOL
