// Copyright 2026 Jaakko Lipponen
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Finnish Sofle Pro layout. The host OS layout is Finnish (Windows and Linux).
// Layer images: docs/layers/ (generated by tools/keymap/gen_layers.py).

#include QMK_KEYBOARD_H
#include "keymap_finnish.h"
#include "sendstring_finnish.h"
#include "features/keycodes.h"
#include "features/fi_keys.h"

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    /* BASE: Finnish QWERTY. Backspace on the right thumb, Å right of P. */
    [_BASE] = LAYOUT(
    KC_ESC,  FI_1,    FI_2,    FI_3,    FI_4,    FI_5,                                FI_6,    FI_7,    FI_8,    FI_9,    FI_0,    FI_PLUS,
    KC_TAB,  FI_Q,    FI_W,    FI_E,    FI_R,    FI_T,                                FI_Y,    FI_U,    FI_I,    FI_O,    FI_P,    FI_ARNG,
    CTL_ESC, FI_A,    FI_S,    FI_D,    FI_F,    FI_G,                                FI_H,    FI_J,    FI_K,    FI_L,    FI_ODIA, FI_ADIA,
    KC_LSFT, FI_Z,    FI_X,    FI_C,    FI_V,    FI_B,    KC_MUTE,          KC_MPLY,  FI_N,    FI_M,    FI_COMM, FI_DOT,  FI_MINS, KC_RSFT,
                      KC_LGUI, KC_LALT, KC_LCTL, KC_SPC,  MO(_NAV),         MO(_SYM), KC_BSPC, KC_ENT,  KC_ALGR, TG(_NUM)
    ),

    /* NUM (toggle): numpad on the right, spreadsheet keys on the left. */
    [_NUM] = LAYOUT(
    _______, _______, _______, _______, _______, _______,                             KC_ESC,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS, _______,
    _______, _______, KC_HOME, KC_UP,   KC_END,  KC_PGUP,                             FI_COMM, KC_P7,   KC_P8,   KC_P9,   KC_PPLS, _______,
    _______, KC_F2,   KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN,                             FI_DOT,  KC_P4,   KC_P5,   KC_P6,   KC_PPLS, _______,
    _______, C(KC_Z), C(KC_X), C(KC_C), C(KC_V), XXXXXXX, _______,          _______,  FI_EQL,  KC_P1,   KC_P2,   KC_P3,   KC_PENT, _______,
                      _______, _______, _______, _______, _______,          KC_P0,    _______, _______, KC_PDOT, TG(_NUM)
    ),

    /* SYM (hold right big thumb): opening brackets left, closing mirrored right.
       Top row: dead keys for accents (left) and typography (right). */
    [_SYM] = LAYOUT(
    FI_SECT, FI_ACUT, FI_GRV,  FI_DIAE, FI_CIRC, FI_TILD,                             FI_EURE, TY_NDSH, TY_MDSH, TY_RDQU, TY_RSQU, TY_DEG,
    _______, FI_EXLM, FI_AT,   FI_HASH, FI_DLR,  FI_PERC,                             CIRC_LIT,FI_AMPR, FI_ASTR, FI_PLUS, FI_QUES, _______,
    KC_BSPC, FI_QUOT, FI_LCBR, FI_LPRN, FI_LBRC, FI_EQL,                              FI_SLSH, FI_RBRC, FI_RPRN, FI_RCBR, FI_DQUO, FI_BSLS,
    _______, GRV_LIT, FI_LABK, FI_PIPE, TILD_LIT,FI_SCLN, _______,          _______,  XXXXXXX, FI_COLN, FI_MINS, FI_RABK, FI_UNDS, _______,
                      _______, QK_LLCK, _______, _______, MO(_FUN),         _______,  _______, _______, _______, _______
    ),

    /* NAV (hold left big thumb): arrows right, held mods and editing left. */
    [_NAV] = LAYOUT(
    KC_MUTE, KC_VOLD, KC_VOLU, KC_MPRV, KC_MPLY, KC_MNXT,                             OS_SHOT, OS_DESKL,OS_DESKR,G(KC_L), KC_CALC, XXXXXXX,
    _______, ALT_TAB, C(KC_PGUP),C(KC_PGDN),A(KC_LEFT),A(KC_RGHT),                    KC_PGUP, KC_HOME, KC_UP,   KC_END,  KC_INS,  _______,
    _______, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, CW_TOGG,                             KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_DEL,  _______,
    _______, C(KC_Z), C(KC_X), C(KC_C), C(KC_V), OS_REDO, _______,          _______,  XXXXXXX, C(KC_LEFT),XXXXXXX,C(KC_RGHT),XXXXXXX,_______,
                      _______, _______, _______, _______, _______,          MO(_FUN), _______, _______, QK_LLCK, _______
    ),

    /* FUN (NAV + SYM): F-keys in the NUM digit spots, mods on the left. */
    [_FUN] = LAYOUT(
    KC_F13,  KC_F14,  KC_F15,  KC_F16,  KC_F17,  KC_F18,                              KC_F19,  KC_F20,  OVL_PIN, CLAUDE_ACK,KC_SCRL,KC_PAUS,
    QK_BOOT, MS_WHLU, MS_BTN1, MS_UP,   MS_BTN2, XXXXXXX,                             OS_MODE, KC_F7,   KC_F8,   KC_F9,   KC_F12,  RM_TOGG,
    _______, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, XXXXXXX,                             KC_CAPS, KC_F4,   KC_F5,   KC_F6,   KC_F11,  RM_NEXT,
    _______, MS_WHLD, MS_LEFT, MS_DOWN, MS_RGHT, MS_BTN3, _______,          _______,  OLED_TOG,KC_F1,   KC_F2,   KC_F3,   KC_F10,  EE_CLR,
                      _______, QK_LLCK, _______, _______, MO(_FUN),         MO(_FUN), _______, _______, QK_LLCK, _______
    )
};

#ifdef ENCODER_MAP_ENABLE
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU),          ENCODER_CCW_CW(MS_WHLU, MS_WHLD) },
    [_NUM]  = { ENCODER_CCW_CW(KC_LEFT, KC_RGHT),          ENCODER_CCW_CW(KC_UP, KC_DOWN) },
    [_SYM]  = { ENCODER_CCW_CW(C(KC_PGUP), C(KC_PGDN)),    ENCODER_CCW_CW(C(KC_PMNS), C(KC_PPLS)) },
    [_NAV]  = { ENCODER_CCW_CW(OS_DESKL, OS_DESKR),        ENCODER_CCW_CW(C(KC_Z), OS_REDO) },
    [_FUN]  = { ENCODER_CCW_CW(RM_PREV, RM_NEXT),          ENCODER_CCW_CW(RM_VALD, RM_VALU) },
};
#endif
// clang-format on

void keyboard_post_init_user(void) {
    user_config_load();
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (!process_fi_keys(keycode, record)) {
        return false;
    }
    return true;
}

layer_state_t layer_state_set_user(layer_state_t state) {
    return fi_keys_layer_state(state);
}

void housekeeping_task_user(void) {
    fi_keys_housekeeping();
}
