ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes

RGB_MATRIX_ENABLE = yes
# RGBLIGHT_ENABLE = no

VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = no 
PROGRAMMABLE_BUTTON_ENABLE = yes
OS_DETECTION_ENABLE = yes
LAYER_LOCK_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no